### ISSUE TITLE
Opening paragraph tersification

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-planning-and-implementation#100]
Suggested change to:
Do you need to urgently address accessibility in an on-going website development project? Here is a concise overview with pointers to help address the most critical issues. Find a more comprehensive accessibility approach for the entire design and development process in our Planning and Managing Web Accessibility guide.

**Comment by nitedog** [comment]
Changed intro to: "Do you need to urgently address accessibility in an on-going web project? This is a concise overview with pointers to help address the most critical issues. Find a more comprehensive accessibility approach for the entire design and development process in <a href="https://www.w3.org/WAI/impl/Overview">Planning and Managing Web Accessibility</a>".
