### ISSUE TITLE
Intro sentences for Important resources and What is Accessibility sections

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-planning-and-implementation#101]
Each section seems to have an intro sentence that in my opinion simply adds something else to wade through. The section heading generally says it all, often making the sentence redundant and entirely skippable. My suggestions:
1. Important Resources -  Most likely all resources in this guide are important, aren't they? How about Quick Starts for Designers and Developers and then leave out the intro sentence.
2. What is Accessibility - the section title and short phrases that describe each resource are sufficient, drop the intro sentence.

**Comment by nitedog** [comment]
1. Changed first heading from "Important Resources" to "Key Resources for Designers and Developers". These are not really all "quick starts", but I like your idea of including the audience into the heading.
2. Terrsified intro sentence under "what is accessibility?" but kept "if you are new to accessibility" bit to help readers decide if they need to read this section - remember we had a lot of back and forth on including the accessibility intros or not (see issue #70) 
3. Made simplifications and removed intro/warning sentences from "identify the issues" per #102 
4. Used similar approach for "what is accessibility?" section (new heading "more background")
5. Changed "what is your strategy" to "tips for efficient repair" (per #103) and removed intro sentence
