### ISSUE TITLE
Change section title - What is your strategy?

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-planning-and-implementation#103]
This is somewhat jarring since it is not really asking the reader to choose but is actively suggesting a broad strategy that includes several roles and tools. Suggest that be reflecting in the section heading. Maybe something like:

"Broad Strategic Approach"  or something similar. 

I understand that the question format fits with previous section titles so do not feel strongly. 

Also each bullet here can be tersified as well.

**Comment by shawna-slh** [comment]
Related: I'm not keen on the headings being questions. I think it's OK for the first "What is Accessibility?" -- but for the others, we're telling them to figure that out, not asking them what they already know...

**Comment by AndrewArch** [comment]
How about something like:
- Important Resources
- What is Accessibility?
- Identify the issues
- consider the scope
- set your accessibility target level
- Broad Strategic Approach
- Longer Term: Planning and Managing

**Comment by nitedog** [comment]
Changed to:
- Key Resources for Designers and Developers
- What is Accessibility?
- Identify the Issues
- Consider the Scope
- Set your Accessibility Target Level
- Tips for Efficient Repair
- Longer Term: Planning and Managing
