### ISSUE TITLE
[Improving the Accessibility of Your Website]

### ISSUE THREAD

**Issue by brewerj** [w3c/wai-planning-and-implementation#111]
This is a comment related to the page [Improving the Accessibility of Your Website](//w3c.github.io/wai-planning-and-implementation/improving.html) Reconsider placement under WAI nav 

This updated doc looks like it might belong better under Getting Started now.

**Comment by yatil** [comment]
I close this issue as we are have been working on the new IA in the w3c/wai-website-design TF. Feel free to reopen it if you feel it needs discussion.
