### ISSUE TITLE
[Developing Organizational Policies on Web Accessibility] layout in IE 11

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#112]
This is a comment related to the page [Developing Organizational Policies on Web Accessibility](https://w3c.github.io/wai-planning-and-implementation/pol.html)

Note spacing around navigation, especially of the box under "Example of simple policy".

<img width="960" alt="pol-clip" src="https://cloud.githubusercontent.com/assets/6991814/21208224/6824dd72-c232-11e6-8861-43703e745285.png">

For comparison:

<img width="960" alt="contact-orgs-clip" src="https://cloud.githubusercontent.com/assets/6991814/21208228/6f400672-c232-11e6-892e-fe1d78ab44a4.png">

**Comment by yatil** [comment]
Is this still an issue? It should work with the redesigned site.
