### ISSUE TITLE
[Developing Organizational Policies on Web Accessibility] - Example Comprehensive Policy

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-planning-and-implementation#113]
This is a comment related to the page [Developing Organizational Policies on Web Accessibility](//w3c.github.io/wai-planning-and-implementation/pol.html)

In the [Example Policies](https://www.w3.org/WAI/impl/pol#examples) section of the page, the link to the Example Comprehensive Policy is 404.

**Comment by yatil** [comment]
It is available on GitHub, so I guess it was just not copied over? http://w3c.github.io/wai-planning-and-implementation/examplepolicy

Assigns @nitedog because I’m otherwise occupied at the moment :-)

**Comment by nitedog** [comment]
Yes, not copied. I call upon @yatil the great to cast another magical spell...

**Comment by yatil** [comment]
Done; w/o magic, just ordinary work.

https://www.w3.org/WAI/impl/examplepolicy

**Comment by bakkenb** [comment]
Thank you very much!!!
