### ISSUE TITLE
spacing around examples

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#22]
There is a lot of spacing around the examples. I think this breaks the flow in a negative way and separates them too much from the sections they belong to. (and gives them too much visual focus) I suggest much less space between the heading "Examples" and the first example, as well as between multiple examples in the same section.

**Comment by iadawn** [comment]
This is something that I need to look at as there is a separate comment that there is not enough to distinguish each example. I think this may be from a screen reader perspective and was considering how I might put in sub-headings for each example (just Example 1, Example 2 etc) as one option.

**Comment by shawna-slh** [comment]
Yes, that comment is from screen reader user. :-) Could you go ahead and put in subheadings. Maybe be more descriptive than just Example 1, Example 2 -- something more like Simple Example, Detailed Example?

**Comment by iadawn** [comment]
I will have a think about this as it will most likely require a change in the code. Also, I am not sure that all the examples lend themselves to descriptive sub-headings.

**Comment by iadawn** [comment]
Subheadings have been added as off-screen elements. Have also reduced space slightly between examples. Don't want to go to far as I think they may merge a little bit too much for some readers.
