### ISSUE TITLE
[improving] no expand-collapse

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#29]
[strong]
I think we should not have expand-collapse on this page, for several reasons, e.g.:
- It doesn't collapse most of the content. Unlike the Planning & Managing pages, it doesn't let the user see all of the headings at the top of the page, mostly above the fold.
- The "expand all sections" button is visible without the [+]'s being visible, so it's not as clear what it does, even after you click it. If user ignores it, then later gets to the [+] and decides they want to expand all, then have to scroll back up to the button.

**Comment by iadawn** [comment]
I think when this was initially prepared the approach in [Easy Checks](https://www.w3.org/WAI/eval/preliminary.html) was adopted, which has a similar problem.

In this instance I am also a bit concerned that we are walking into a wall of text. It may be that if the expand/collapse is removed (or even if not) then some slight tweaks to the spacing between the sections, and the stuly of sub-headings might be beneficial.

**Comment by shawna-slh** [comment]
One HUGE difference with most of the expand-collapses in Easy Checks is that they are _mostly used for guidance on specific toolbars_. This makes sense -- a user with only X toolbar shouldn't have to wade through instructions for other toolbars.

In Easy Checks, right after the "expand all sections" button, there are instructions "Click headings with [+] buttons to get hidden information".

I don't think this resource warrants this.

I agree tweaks to styling is what this resource needs. :)

**Comment by iadawn** [comment]
OK, @nitedog and I have had a chat and I am going to try and change the style of it to be much more aligned with the Planning and Managing resource. So each of the sections becomes an expand collapse with a small blurb and the Page contents and 'Key steps for accessibility improvement' are removed. The aim is to make it much more skimable as well as improving the consistency across resources... a bit!

**Comment by shawna-slh** [comment]
The document is currently out to EOWG for Thorough Review. If you are making content changes, I think we need to PAUSE the review. If so, we should notify EOWG ASAP -- at least with an update in Work for this Week and the Weekly Survey. <--- @bakkenb  @sharronrush

**Comment by iadawn** [comment]
The content changes are confined to the in-page navigation only. The main suggestion was to explore the style of the page in light of your comments, the changes to Planning and Managing, and the relationship between this document and Planning and Managing.

What are your thoughts on the suggested approach?

**Comment by nitedog** [comment]
Actually I missed that point. @slhenry is right, we should not make any changes now. I suggest we hold this change (rather than the review!) until after the review. The group would also be more up to speed to discuss this point after the review.

**Comment by yatil** [comment]
I agree with no expand/collapse, at least not for sub-items. They seem short enough to just have them in the text.

**Comment by iadawn** [comment]
I have pulled together an example of what I was talking about for folks to look at; [Improving with expand/collapse](http://w3c.github.io/wai-planning-and-implementation/improving_excol.html).

As I failed to explain, I have made this more like the [Planning and Managing](http://w3c.github.io/wai-dynamic-planning/initiate/) pages. I have not included the share links as yet, but that is a likely addition, and the blurb text for each section is by no means perfect.

Thoughts?

**Comment by shawna-slh** [comment]
While I feel strongly that we don't want ex/col on the key points, I do not feel strongly either way about having them on the h2s.

I do _not_ think we need to match Planning and Managing if we decide they are not as useful on this resource -- e.g., in Planning and Managing, people are more likely to want read one or a couple sections, and not the whole page at a time; whereas in this and the Policy page, people will usually read & print the whole thing.

I think the Share links would be more clutter than useful in this doc (and probably in the Policy doc as well).

**Comment by iadawn** [comment]
Cleared out expand collapse and improved styling for key actions.
