### ISSUE TITLE
Move "What is this document for?" section.

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-planning-and-implementation#31]
This would be more helpful for users if it's at the top of the page. As it stands, they must read through three lengthy paragraphs before getting to a concise description of the content.

**Comment by bakkenb** [comment]
I agree with @susanatx about the location of this text. Should be up at the top.

**Comment by iadawn** [comment]
@slhenry and I have made some changes to the opening paragraphs. Does this address your concerns?

**Comment by susanatx** [comment]
Looks great.
