### ISSUE TITLE
[pol] [impl] Duplicate navigation

### ISSUE THREAD

**Issue by yatil** [w3c/wai-planning-and-implementation#33]
I see that the _On this Page_ navigation is easily lost, but repeating (almost but not quite all of) it inline makes little sense for me.

Suggestion: Remove _On this Page_ navigation completely, add remaining items to the inline navigation section – either as a separate list or inline, for example:

> Consider begining with a simple policy statement and expanding upon it with the following topics:
> - Reference Standards
> - Define Conformance Levels
> - Define Scope of Policy
> - Set Conformance Milestones
> - Consider Third-party Content
> - Define Monitoring and Review Process
> - _Next Steps:_ Maintaining your policy
> - _Long term:_ Strategic Planning

**Comment by iadawn** [comment]
I have stuck with the 'on this page' navigation as it is the broad standard for the rest of the WAI site. I have removed the repetition though.
