### ISSUE TITLE
[pol] Inline links instead of paragraphs

### ISSUE THREAD

**Issue by yatil** [w3c/wai-planning-and-implementation#35]
Related to #34 – Would it be possible to have links to the overviews inline instead of in separate paragraphs, I have the feeling that this is just making the page longer and reinforces the Wall-of-Text problem.

**Comment by iadawn** [comment]
I think that the issue of inline links has been discussed with other resources with a mild preference for avoiding inline links. The wall of text, I think, could be combated with a few other design alterations, but I will keep this idea in mind.
