### ISSUE TITLE
[Improving the Accessibility of Your Website] real users too much for many

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#54]
This is a comment related to the page [Improving the Accessibility of Your Website](//w3c.github.io/wai-planning-and-implementation/improving.html)

We've said the target audience for this is people in the situation of: "HELP! I have to fix my website NOW!"

They might freak out from the key action of "Evaluate with real users." and "User experience testing and reporting is therefore an important measure of the impact of accessibility barriers." Of course it's the right thing to do, but I wonder if we might want to make it softer -- a strongly recommended suggestion, but not a "requirement".

I notice the wording in the [previous draft](https://www.w3.org/WAI/EO/Drafts/Improving2012) is a little softer and tells about the benefit, but doesn't make it a "key action".: "To get a rough idea of the type and amount of accessibility barriers on your website, you can do some initial evaluation. Preliminary Review... Involving Users in Web Accessibility Evaluation provides guidance on including people with disabilities ("users") in accessibility evaluation throughout web development. In addition to helping identify and prioritize accessibility barriers, watching people struggle to use your site can be a powerful motivator for your retrofitting project team.", "Evaluating with users with disabilities also helps determine the impact of accessibility barriers in your website.", "Involving users with disabilities and having accessibility specialists evaluate your planned repairs can catch any problems before they are propagated throughout your site."

**Comment by iadawn** [comment]
Toned down the wording. 'Key actions' may not be the right term for any of these, however I would rather keep them as scannable bullets than lose them. This is slightly related to a comment in #53
