### ISSUE TITLE
[Improving the Accessibility of Your Website] Implement weak

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#55]
This is a comment related to the page [Improving the Accessibility of Your Website](//w3c.github.io/wai-planning-and-implementation/improving.html)

The Implement section is very weak, and the text doesn't seem to fit with the key action. Is there stuff from the [previous version](https://www.w3.org/WAI/EO/Drafts/Improving2012) (or possibly the [Start with page](https://www.w3.org/WAI/EO/wiki/Start_with_Accessibility)) that fits here? Or does it need some re-organization and different headings? And/or a pointer to appropriate section(s) of Planning and Managing?

**Comment by iadawn** [comment]
Added in more to this section.

The Start with Accessibility page may has some valuable stuff in it but the difficulty is that it is tied to quite a specific development model. I have reviewed the relevant sections.
