### ISSUE TITLE
Content across resources

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#56]
Now that things are settled, it would be good to go over the related resources and make sure we have all previously written content where we want it, and appropriate pointers to related info.

new/updated resources:
- Planning & Managing
- Improving
- Policies

previous sources:
- Implementation Plan
- [Implementing previous version](https://www.w3.org/WAI/EO/Drafts/Improving2012)
- [Start with page](https://www.w3.org/WAI/EO/wiki/Start_with_Accessibility)

For example, maybe there would be a few (but not too many!) specific places in Improving where we want to point to Planning & Managing?

**Comment by iadawn** [comment]
I have left linking to the Planning and Managing to two points in the document; at the start, just in case the reader is inadvertantly in the wrong place; and at the end as a natural follow on. I have avoided any links in the middle to avoid distracting too much.

The previous resources have been review a number of times. The "Start with accessibility" page is something where I have taken various bits from but there is still a lot in there that doesn't quite fit in either Planning & Managing or in Improving. This may be something for further discussion.
