### ISSUE TITLE
[Improving the Accessibility of Your Website] For Editor’s Discretion: Remove back to top links

### ISSUE THREAD

**Issue by yatil** [w3c/wai-planning-and-implementation#64]
This is a comment related to the page [Improving the Accessibility of Your Website](//w3c.github.io/wai-planning-and-implementation/improving.html)

@slhenry brought up that we might not need the back to top links as this is quite short. I think I agree but defer the decision to @nitedog.

**Comment by nitedog** [comment]
Agreed.
