### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-planning-and-implementation#71]
I'm getting a 404 on:
- all links under "Understand the Basics"
- all links under "Explore the Issues"
- the "List of Web Accessibility Evaluation Tools" link under "Optimize Your Tools"
- the "Tips for Getting Started" link under "Implement Repairs"

**Comment by yatil** [comment]
Relative links are used. You can replace w3c.github.io to w3.org and should get to the appropriate page on W3.org.

**Comment by nitedog** [comment]
Fixed links.
