### ISSUE TITLE
Comments on latest version of “Short Term Website Accessibility Improvements”

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-planning-and-implementation#73]
I agree that the first paragraph could be re-written.  My initial thoughts were to say something like Critical enhancements you can make to increase access to your site while initiating a long-term accessibility plan (or strategy).

I think you could move “Prioritize the Repairs” and “Implement the Repairs” sections above the “Get Help” and “Evaluate your Content” sections.  They are more concrete and relate directly to the “Explore the Issues” and “Define your Scope” sections.

I hope this helps.  I like that you have “Planning and Managing Accessibility” at the beginning and end of this document stressing that this document is guidance only on how to make immediate improvements and is not a substitute for organizational policy.

**Comment by shawna-slh** [comment]
+1 to rewriting first paragraph

0 (not sure about) to changing the order. Would like short discussion on that. (See also related comment https://github.com/w3c/wai-planning-and-implementation/issues/78)

+1 to “Planning and Managing Accessibility” at the beginning and end -- although I'm not sure about "companion document"

**Comment by nitedog** [comment]
I've revised the entire introduction, and also re-ordered and combined several sections. "Get Help" was removed. Please re-open issue if changes are not adequate. Ping @lakeen @slhenry
