### ISSUE TITLE
Broken link - "example comprehensive policy"

### ISSUE THREAD

**Issue by benjiallen** [w3c/wai-planning-and-implementation#79]
This is a comment related to the page [Developing Organizational Policies on Web Accessibility](//w3c.github.io/wai-planning-and-implementation/pol.html)

I get a 404 when I try to access the [example comprehensive policy](https://www.w3.org/WAI/impl/examplepolicy) link on the page.

**Comment by nitedog** [comment]
@benjiallen Thanks! This is because this is an editor draft on GitHub, so not all links work. Please refer to the latest stable version on the WAI website: https://www.w3.org/WAI/impl/pol
