### ISSUE TITLE
[Improving] content relevant to people with disabilities

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#83]
about:
- "content that is particularly relevant to people with disabilities"
- "Are specifically relevant to people with disabilities"

I have mixed reactions to these. It seems:
- Such a tiny percent of web content is specifically/particularly relevant to people with disabilities.
- It's kind of "a no brainer" / common sense to include such content in prioritizing.
- Does this risk feeding misunderstandings that people with disabilities use _all_ content? I can hear an uninformed person saying, "Well, that content is not intended for people with disabilities, so we didn't make it accessible".

I lean slightly towards taking these out (but only slightly :-).

**Comment by nitedog** [comment]
I removed "Are specifically relevant to people with disabilities", as this was a stand-alone list item and more prone to misunderstanding. I think the other part may be helpful in some situations. Please re-open issue if changes are not adequate. Ping @slhenry
