### ISSUE TITLE
[Improving] edit need for clarity and simplification

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#87]
<blockquote>You may need help from people with more expertise in web accessibility from outside your team. These could be individuals working in other parts of your organization or consultants external to the organization. You might not need help with every task. The more background you have in accessibility and the skills available in your team and organization, the better you will be able to leverage them.</blockquote>

This seems unnecessarily wordy, and also unclear. What are the key points we want to get across here?

**Comment by nitedog** [comment]
This section was removed. Please re-open issue if changes are not adequate. Ping @slhenry
