### ISSUE TITLE
[Improving] huh?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#89]
<blockquote>Requires less testing with users (user experience repairs)</blockquote>

I don't understand "(user experience repairs)" here.

**Comment by nitedog** [comment]
Changed to "Requires less testing with end-users (eg. user experience)". Please re-open issue if changes are not adequate. Ping @slhenry

**Comment by shawna-slh** [comment]
I have mixed reactions to this point overall. I feel like most people would be, "How do I know what requires less testing with users?!?" In that case it seems like **this point has more potential to cause confusion and frustration than be helpful**. I do not feel strongly about it. It might be worth a little EOWG discussion to get more perspectives.
/me rethinks self... Maybe it's OK 'cause even if they don't understand it at first, maybe they will at some point...

If we do leave the point, I don't think "end-users" is needed - "users" seems simpler and sufficient.

Also, I don't think "(eg. user experience)" adds much information and does add some complexity and possibility for further confusion. (This from a long-time user experience professional -- before it was even called that ;-)

> Requires less testing with users

**Comment by James-Green** [comment]
I would remove the entire bullet and take regression and by others off the 2nd bullet, allowing it to cover the point made by the 3rd. Like this:

Low-effort repairs
- Require less time, cost, or skills to repair
- Requires less testing and validation

**Comment by nitedog** [comment]
@slhenry does this change address your concern?

**Comment by yatil** [comment]
+1 to this change

**Comment by shawna-slh** [comment]
yes.

**Comment by nitedog** [comment]
Changes by @James-Green merged.
