### ISSUE TITLE
[medium] Possible Link Addition

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-planning-and-implementation#97]
- Priority: [medium]
- Location: What is your Scope? / High-impact repairs / WCAG level A issues
- Suggested Revision: Add a link in this bullet that goes to the Quickref with it filtered to show all Level A success criteria
- Rationale: Some users of this page will be completely new to accessibility and won't know what is meant by WCAG Level A. Would help to point them to a list of them so they can start reviewing and understanding them if they choose.

**Suggested change in content would be:** 
Web Content Accessibility Guidelines (WCAG) <a href=https://www.w3.org/WAI/WCAG20/quickref/?currentsidebar=%23col_customize&levels=aa%2Caaa>Level A issues</a>

**Comment by susanatx** [comment]
I like this. It cuts down on some of the basic stuff and takes people straight to the source if they feel ready for that.

**Comment by nitedog** [comment]
Addressed by #95
