### ISSUE TITLE
[medium] What are the Issues? section - Wording edit

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-planning-and-implementation#98]
- Priority: [medium] Editors discretion
- Location: What are the Issues? / First paragraph
- Current Wording: "If you already know the specific issues you need to address, you can skip this section. If you are starting to address accessibility without background, the following manual helps you get a rough idea of the current situation on your website:"
- Suggested Revision: "If you already know the specific issues you need to address, you can skip this section. If you are starting to address accessibility without background, the following <b>resource</b> helps you <b>quickly</b> get a rough idea of the current situation on your website:"
- Rationale: clarification

**Comment by nitedog** [comment]
Included suggestion in #95
