### ISSUE TITLE
[medium] Longer Term Section - Wording Edit

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-planning-and-implementation#99]
- Priority: [medium] Editors discretion
- Location: Longer Term: Planning and Managing section
- Current Wording: "Once you have addressed some of the most critical web accessibility issues on your website and begun to address the rest, it is essential you plan to integrate accessibility throughout the design and development process. ..."
- Suggested Revision: "Once you have addressed some of the most critical web accessibility issues **with** your **web project, continue** to address the rest**. It** is essential you plan to integrate accessibility throughout the design and development process. ..."
- Rationale: Expand beyond web "sites," and a call for them to go on to the next step.

**Comment by nitedog** [comment]
Changed sentence to "Once you have addressed some of the most critical web accessibility issues on your web project, it is essential you plan to integrate accessibility throughout future design and development processes".
